#!/bin/sh
mvn clean package && docker build -t saurabhsali/CustomerClient1 .
docker rm -f CustomerClient1 2>/dev/null || true && docker run -it --name CustomerClient1 -p 8080:8080 -p 4848:4848 -p 8181:8181 --name CustomerClient1 saurabhsali/CustomerClient1
